$ANSIBLE_VAULT;1.1;AES256
38333465613265343763613963613837643462326132343534643735386431336434613866663432
3866313165333638356666383664643264663463623666620a656265373261373464333864633133
30383938653633363466323331323333386339353639396638646430333963653635636633323933
6431336339333231370a636537336538313964636438636463323633333134616535323037386134
63343135333137313535303761623266323330306330386433633163643735623430346664386464
37363164363663353361663131653839623261643662613234336362613766613739646532376134
37353862316533313333303366636237383764393136653566303731353135373138386130356362
31336362666263373536306633373766366664626231663438663233643665613533613035356230
31346534653035376464303434616137343865316336653162303566353662363839363131346537
61386365313164343834386537373231373934373336633037653262323162363530646432643235
63643231663765626130386230643533656166323135373333366163633866333238626535353030
31303065363237396537326534626462313330626164336436643661383561363139376635646661
36373332363763643530396539323465326431366161666265656231616561363433356339306666
36623862323830303935626338316265346664333430666636633061653735383463613966613730
33313861333461366336626665643937393566353136376262656132393535646532656263313465
34643662316435386630653934333332633764336330656233663339346435366461646263306137
32626230383933386635616234653263623830373734343136313661303336623436
